# Generated by Django 3.2 on 2022-07-02 16:44

import ckeditor_uploader.fields
import common.yandex_storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('description_kk', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание (каз)')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание (рус)')),
                ('project_type', models.CharField(choices=[('reqular', 'Обычный'), ('special', 'Спецпроекты')], default='reqular', max_length=16)),
                ('status', models.CharField(choices=[('in_process', 'В процессе'), ('on_pause', 'В паузе'), ('finished', 'Завершен')], default='in_process', max_length=16)),
                ('unique_id', models.CharField(max_length=255, unique=True, verbose_name='Униакальное id')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('description_kk', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание (каз)')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание (рус)')),
                ('required_amount', models.PositiveIntegerField(verbose_name='Нужно собрать')),
                ('collected_amount', models.PositiveIntegerField(verbose_name='Собрано')),
                ('year', models.PositiveIntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('status', models.CharField(choices=[('in_process', 'В процессе'), ('on_pause', 'В паузе'), ('finished', 'Завершен')], default='in_process', max_length=16)),
                ('unique_id', models.CharField(max_length=255, unique=True, verbose_name='Униакальное название')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.project')),
            ],
            options={
                'verbose_name': 'Проект (годы)',
                'verbose_name_plural': 'Проекты (по годам)',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('file', models.FileField(blank=True, storage=common.yandex_storage.ClientDocsStorage, upload_to='projects-resourses', verbose_name='Файл')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.projectperiod')),
            ],
            options={
                'verbose_name': 'Ресурс (проект)',
                'verbose_name_plural': 'Ресурсы (проект)',
                'ordering': ['-created_at'],
            },
        ),
    ]
