# Generated by Django 3.2 on 2022-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_process', 'В процессе'), ('on_pause', 'В паузе'), ('finished', 'Завершен')], default='in_process', max_length=16),
        ),
        migrations.AlterField(
            model_name='projectperiod',
            name='status',
            field=models.CharField(choices=[('in_process', 'В процессе'), ('on_pause', 'В паузе'), ('finished', 'Завершен')], default='in_process', max_length=16),
        ),
    ]
