# Generated by Django 3.2 on 2022-06-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220622_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectperiod',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.project'),
        ),
    ]
