# Generated by Django 3.2 on 2022-07-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_donation_key'),
        ('projects', '0002_project_donat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='donat',
        ),
        migrations.RemoveField(
            model_name='projectperiod',
            name='collected_amount',
        ),
        migrations.RemoveField(
            model_name='projectperiod',
            name='required_amount',
        ),
        migrations.RemoveField(
            model_name='projectperiod',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='projectperiod',
            name='donat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.donation'),
        ),
    ]
