# Generated by Django 3.2 on 2022-06-22 18:16

import common.yandex_storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectperiod_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectperiod',
            options={'ordering': ['-year', '-created_at'], 'verbose_name': 'Проект (годы)', 'verbose_name_plural': 'Проекты (по годам)'},
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('file', models.FileField(blank=True, storage=common.yandex_storage.ClientDocsStorage, upload_to='projects-resourses', verbose_name='Файл')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectperiod')),
            ],
            options={
                'verbose_name': 'Ресурс (проект)',
                'verbose_name_plural': 'Ресурсы (проект)',
                'ordering': ['-created_at'],
            },
        ),
    ]
