# Generated by Django 3.2 on 2022-07-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220705_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='unique_id',
        ),
    ]
