# Generated by Django 3.2 on 2022-06-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220623_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresource',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.projectperiod'),
        ),
    ]
