# Generated by Django 3.2 on 2022-08-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20220809_0048'),
        ('projects', '0005_projectperiod_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectperiod',
            name='donat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.donation'),
        ),
    ]
