# Generated by Django 3.2 on 2024-07-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectperiod_donat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectperiod',
            name='year',
            field=models.PositiveIntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024),
        ),
    ]
