version: '3'

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=garyshker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=garyshker
    volumes:
      - data:/var/lib/postgresql/data/
    expose:
      - "5432"

  web:
    build: .
    command:
      - /bin/sh
      - /app/scripts/entrypoint.sh
    container_name: garyshker_web
    volumes:
      - .:/app
    expose:
      - "8000"
      - "8001-8050"
    env_file: .env.dev
    depends_on:
      - db

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A config worker --loglevel=INFO --concurrency=2
    volumes:
      - .:/app
    env_file: .env.dev
    depends_on:
      - web
      - redis

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./static/:/static/
      - ./media/:/media/
      - ./data/nginx_dev:/etc/nginx/conf.d
    ports:
      - "80:80"
    expose:
      - "8080"
    depends_on:
      - web

  celery-beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file: .env.dev
    depends_on:
      - web
      - db
      - redis
      - celery
volumes:
  data: