version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=garyshker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=garyshker
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    build: .
    command:
      - /bin/sh
      - /app/scripts/entrypoint.sh
    container_name: garyshker_web
    environment:
      - localhost
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      ./.env
    depends_on:
      - db
volumes:
  postgres_data: