# Generated by Django 3.2 on 2022-07-02 16:44

import common.yandex_storage
import course.models.course
import course.models.resource
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obrazovanie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('bookmarks_count', models.PositiveIntegerField(default=0, verbose_name='Сохранения')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (каз)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('duriation', models.DurationField(blank=True, default='7 00:00:00', verbose_name='Длительность курса')),
                ('to_view', models.BooleanField(default=False, verbose_name='Доступна для показа')),
                ('views', models.PositiveIntegerField(default=0)),
                ('teaser', models.FileField(blank=True, null=True, storage=common.yandex_storage.ClientDocsStorage, upload_to=course.models.course.course_teaser_dir, verbose_name='Тизер')),
                ('image', models.FileField(blank=True, upload_to='course-image', verbose_name='Обложка')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Оценка')),
                ('lesson_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_category', to='obrazovanie.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('role_kk', models.TextField(max_length=500, null=True, verbose_name='Сфера деятельности (каз)')),
                ('role_ru', models.TextField(max_length=500, null=True, verbose_name='Сфера деятельности (рус)')),
                ('description_kk', models.TextField(max_length=500, null=True, verbose_name='Описание (каз)')),
                ('description_ru', models.TextField(max_length=500, null=True, verbose_name='Описание (рус)')),
                ('icon', models.ImageField(blank=True, default='garysh.jpg', null=True, upload_to='lector', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Лектор',
                'verbose_name_plural': 'Лекторы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (каз)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('duriation', models.DurationField(blank=True, verbose_name='Длительность')),
                ('video', models.CharField(blank=True, default='', max_length=6250, verbose_name='Название видео с расширением)')),
                ('views', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='course.course')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_lector', to='course.lector')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (каз)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('duriation', models.DurationField(blank=True, verbose_name='Длительность')),
                ('video', models.CharField(blank=True, default='', max_length=6250, verbose_name='Название видео с расширением)')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_module_course', to='course.course')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_module_lector', to='course.lector')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (каз)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('file', models.FileField(blank=True, storage=common.yandex_storage.ClientDocsStorage, upload_to=course.models.resource.course_dir, verbose_name='Файл')),
                ('link', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылка')),
                ('image', models.FileField(blank=True, upload_to=course.models.resource.course_resource, verbose_name='Обложка')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
                ('lesson_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lessonmodule')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('access', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='modules',
            field=models.ManyToManyField(blank=True, to='course.LessonModule', verbose_name='Модули'),
        ),
        migrations.AddField(
            model_name='course',
            name='lectors',
            field=models.ManyToManyField(blank=True, editable=False, to='course.Lector'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
