# Generated by Django 3.2 on 2022-03-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obrazovanie', '0003_auto_20220315_2317'),
        ('organizations', '0002_auto_20220316_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('description_kk', models.TextField(max_length=500, null=True, verbose_name='Описание (каз)')),
                ('description_ru', models.TextField(max_length=500, null=True, verbose_name='Описание (рус)')),
                ('icon', models.ImageField(blank=True, default='garysh.jpg', null=True, upload_to='lector', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Лектор',
                'verbose_name_plural': 'Лекторы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_category', to='obrazovanie.category', verbose_name='Категория')),
                ('lectors', models.ManyToManyField(blank=True, editable=False, null=True, to='course.Lector')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
