# Generated by Django 3.2 on 2022-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='role_kk',
            field=models.TextField(max_length=500, null=True, verbose_name='Сфера деятельности (каз)'),
        ),
        migrations.AddField(
            model_name='lector',
            name='role_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Сфера деятельности (рус)'),
        ),
    ]
