# Generated by Django 3.2 on 2022-06-29 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('obrazovanie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonmodule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_module_course', to='course.course'),
        ),
        migrations.AddField(
            model_name='lessonmodule',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_module_lector', to='course.lector'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='course.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_lector', to='course.lector'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='modules',
            field=models.ManyToManyField(blank=True, to='course.LessonModule', verbose_name='Модули'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_category', to='obrazovanie.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='course',
            name='lectors',
            field=models.ManyToManyField(blank=True, editable=False, to='course.Lector'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
