# Generated by Django 3.2 on 2022-04-08 09:56

import course.models.resource
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220406_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.FileField(blank=True, upload_to=course.models.resource.course_resource, verbose_name='Обложка'),
        ),
    ]
