# Generated by Django 3.2 on 2022-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_quizquestionprogress_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
