# Generated by Django 3.2 on 2022-07-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
