# Generated by Django 3.2 on 2022-07-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_videourl_content_type'),
        ('course', '0002_auto_20220714_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.videourl'),
        ),
    ]
