# Generated by Django 3.2 on 2022-03-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220325_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duriation',
            field=models.DurationField(blank=True, default='7 00:00:00', verbose_name='Длительность курса'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
