# Generated by Django 3.2 on 2022-04-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_resource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (каз)'),
        ),
        migrations.AlterField(
            model_name='lessonmodule',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (каз)'),
        ),
    ]
