# Generated by Django 3.2 on 2022-07-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_teaser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
    ]
