# Generated by Django 3.2 on 2022-07-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_videourl_content_type'),
        ('course', '0004_remove_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.videourl'),
        ),
    ]
