# Generated by Django 3.2 on 2022-04-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_participant_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (каз)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (каз)'),
        ),
    ]
