# Generated by Django 3.2 on 2022-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220410_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
