# Generated by Django 3.2 on 2022-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='max_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
