# Generated by Django 3.2 on 2022-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20220411_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
