# Generated by Django 3.2 on 2022-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_lesson_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сохранения'),
        ),
        migrations.AddField(
            model_name='course',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='course',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
