# Generated by Django 3.2 on 2022-04-28 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField(default=1000)),
                ('currency', models.CharField(default='KZT', max_length=32)),
                ('capture_method', models.CharField(default='AUTO', max_length=12)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('attempts', models.PositiveBigIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('card_id', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
