# Generated by Django 3.2 on 2022-07-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20220705_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonation',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED')], default=0),
        ),
    ]
