# Generated by Django 3.2 on 2022-07-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Донат проекты', 'verbose_name_plural': 'Донаты проекты'},
        ),
        migrations.AlterModelOptions(
            name='userdonation',
            options={'verbose_name': 'Донат', 'verbose_name_plural': 'Донаты'},
        ),
        migrations.RemoveField(
            model_name='donation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userdonation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userdonation',
            name='object_id',
        ),
        migrations.AddField(
            model_name='userdonation',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='donat', to='payment.donation'),
        ),
        migrations.AddField(
            model_name='userdonation',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdonation',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
