# Generated by Django 3.2 on 2022-06-30 19:29

import ckeditor_uploader.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0003_donationorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='capture_method',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.AddField(
            model_name='donation',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'id__in': (4, 5, 35, 56)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='donation',
            name='default_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1000, 2000, 5000, 10000, 20000], size=None),
        ),
        migrations.AddField(
            model_name='donation',
            name='description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Id элемента'),
        ),
        migrations.AddField(
            model_name='donation',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
