# Generated by Django 3.2 on 2022-07-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_userdonation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='key',
            field=models.CharField(max_length=255, default='kit_2022'),
        ),
    ]
