# Generated by Django 3.2 on 2022-07-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20220705_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Донат проекты', 'verbose_name_plural': 'Донат проекты'},
        ),
        migrations.RemoveField(
            model_name='userdonation',
            name='client',
        ),
    ]
