# Generated by Django 3.2 on 2022-07-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_delete_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonation',
            name='amount_clear',
            field=models.ImageField(default=100, upload_to=''),
        ),
    ]
