# Generated by Django 3.2 on 2022-08-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_userdonation_amount_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AddField(
            model_name='donation',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
