# Generated by Django 3.2 on 2022-03-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_attempt_testresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
