# Generated by Django 3.2 on 2022-03-27 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('quiz', '0004_alter_test_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_test', to='course.lesson', verbose_name='Урок'),
        ),
    ]
