# Generated by Django 3.2 on 2022-03-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_attempt_selected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_results', to='quiz.test'),
            preserve_default=False,
        ),
    ]
