# Generated by Django 3.2 on 2022-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_testresult_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
