# Generated by Django 3.2 on 2022-04-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
