# Generated by Django 3.2 on 2022-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_test_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='attempt_num',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
