# Generated by Django 3.2 on 2022-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (каз)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='lector', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Организации',
                'verbose_name_plural': 'Организации',
                'ordering': ['-created_at'],
            },
        ),
    ]
