# Generated by Django 3.2 on 2022-03-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (каз)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус)'),
        ),
    ]
