# Generated by Django 3.2 on 2022-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(blank=True, max_length=65535, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=65535, verbose_name='Почта')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Поддержка',
                'verbose_name_plural': 'Поддержка',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('question_ru', models.TextField(blank=True, max_length=65535, null=True, verbose_name='Вопрос (рус)')),
                ('answer_ru', models.TextField(blank=True, max_length=65535, null=True, verbose_name='Ответ (рус)')),
                ('question_kk', models.TextField(blank=True, max_length=65535, null=True, verbose_name='Вопрос (каз)')),
                ('answer_kk', models.TextField(blank=True, max_length=65535, null=True, verbose_name='Ответ (каз)')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
