# Generated by Django 3.2 on 2022-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, max_length=65535, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=65535, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, max_length=65535, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, max_length=65535, null=True, verbose_name='Вопрос'),
        ),
    ]
