# Generated by Django 3.2 on 2022-04-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answer_ru',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_ru',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_kk',
            field=models.TextField(
                blank=True, max_length=65535, null=True, verbose_name='Ответ (каз)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_kk',
            field=models.TextField(
                blank=True, max_length=65535, null=True, verbose_name='Вопрос (каз)'),
        ),
    ]
