# Generated by Django 3.2 on 2022-08-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('email', models.EmailField(blank=True, max_length=65535, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Email заявки',
                'verbose_name_plural': 'Email заявки',
            },
        ),
    ]
