# Generated by Django 3.2 on 2022-04-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20220404_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_ru',
            field=models.TextField(blank=True, max_length=65535, null=True, verbose_name='Ответ (рус)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_ru',
            field=models.TextField(blank=True, max_length=65535, null=True, verbose_name='Вопрос (рус)'),
        ),
    ]
