# Generated by Django 3.2.7 on 2021-10-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20211016_0854'),
        ('support', '0002_auto_20211016_0909'),
        ('support', '0002_auto_20211017_1606'),
    ]

    operations = [
    ]
