# Generated by Django 3.2 on 2022-07-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название города (рус)')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название города (каз)')),
                ('long', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название страны (рус)')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название страны (каз)')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('bookmarks_count', models.PositiveIntegerField(default=0, verbose_name='Сохранения')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название мероприятия (рус)')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название мероприятия (каз)')),
                ('description_ru', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание (рус)')),
                ('description_kk', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание (каз)')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адрес (рус)')),
                ('address_kk', models.CharField(max_length=255, verbose_name='Адрес (каз)')),
                ('address_link', models.CharField(max_length=4096, verbose_name='Адрес (ссылка)')),
                ('event_date', models.DateTimeField(blank=True, verbose_name='Время проведения')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event-posters')),
                ('canceled', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('max_user_count', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.city')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('email', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя человека')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Телефон')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.event')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрация',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='event.country', verbose_name='Страна'),
        ),
    ]
