# Generated by Django 3.2 on 2022-04-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название города (рус)')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название города (каз)')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название мероприятия (рус)')),
                ('name_kk', models.CharField(max_length=255, verbose_name='Название мероприятия (каз)')),
                ('description_ru', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание (рус)')),
                ('description_kk', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание (каз)')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адрес (рус)')),
                ('address_kk', models.CharField(max_length=255, verbose_name='Адрес (каз)')),
                ('address_link', models.CharField(max_length=4096, verbose_name='Адрес (ссылка)')),
                ('event_date', models.DateTimeField(blank=True, verbose_name='Время проведения')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.city')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
    ]
