# Generated by Django 3.2 on 2022-04-15 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_auto_20220415_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_user_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='event_participate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='event_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
