# Generated by Django 3.2 on 2022-11-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220828_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'email', 'phone')},
        ),
    ]
