# Generated by Django 3.2 on 2022-11-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20221117_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
