# Generated by Django 3.2 on 2022-11-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventregistration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=5196, null=True, unique=True),
        ),
    ]
