# Generated by Django 3.2 on 2022-05-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20220508_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='saves',
        ),
        migrations.AddField(
            model_name='event',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сохранения'),
        ),
        migrations.AddField(
            model_name='event',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='event',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='event',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
