# Generated by Django 3.2 on 2022-03-26 09:19

import ckeditor_uploader.fields
import config.yandex_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Название (рус)')),
                ('name_kk', models.CharField(blank=True, default='', max_length=120, verbose_name='Название (каз)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=5000, verbose_name='Путь')),
                ('quality', models.PositiveIntegerField(null=True, verbose_name='Качество')),
                ('width', models.PositiveIntegerField(null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(null=True, verbose_name='Высота')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_kk', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='video-image', verbose_name='Обложка')),
                ('image_2', models.FileField(blank=True, upload_to='video-image', verbose_name='Обложка вторая')),
                ('video', models.FileField(null=True, storage=config.yandex_storage.ClientDocsStorage, upload_to='video-video', verbose_name='Видео')),
                ('video_name', models.CharField(default='', max_length=6250, verbose_name='Название видео с расширением)')),
                ('youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('original_quality', models.PositiveBigIntegerField(null=True, verbose_name='Качество')),
                ('views', models.PositiveIntegerField(default=0)),
                ('subs_kk', models.FileField(blank=True, storage=config.yandex_storage.ClientDocsStorage, upload_to='subtitles', verbose_name='Субтитры (каз)')),
                ('convert_status', models.CharField(choices=[('pending', 'Требуется конвертация'), ('started', 'Конвертируется'), ('converted', 'Конвертирован'), ('error', 'Ошибка')], default='pending', max_length=255, verbose_name='Статус конвертации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_category', to='obrazovanie.category', verbose_name='Категория')),
                ('likes', models.ManyToManyField(blank=True, related_name='video_likes', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='video_saves', to=settings.AUTH_USER_MODEL)),
                ('video_quality', models.ManyToManyField(related_name='video_qualities', to='obrazovanie.VideoQuality')),
            ],
            options={
                'verbose_name': 'Видеролик',
                'verbose_name_plural': 'Видеролики',
                'ordering': ['-created_at', '-views'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Название (рус)')),
                ('title_kk', models.CharField(blank=True, max_length=500, verbose_name='Название (каз)')),
                ('preview_text_ru', models.TextField(blank=True, max_length=1500, verbose_name='Короткое описание (рус)')),
                ('preview_text_kk', models.TextField(blank=True, max_length=1500, verbose_name='Короткое описание (каз)')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_kk', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='report-image', verbose_name='Обложка')),
                ('moderated', models.BooleanField(blank=True, default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_category', to='obrazovanie.category', verbose_name='Категория')),
                ('likes', models.ManyToManyField(blank=True, related_name='report_likes', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='report_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at', '-views'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('likes', models.ManyToManyField(blank=True, default=[], related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments2', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_comment', to='obrazovanie.comment')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
