# Generated by Django 3.2 on 2022-02-15 05:35

import config.yandex_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='', max_length=6250, verbose_name='Название видео с расширением)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, storage=config.yandex_storage.ClientDocsStorage, upload_to='video-video', verbose_name='Видео'),
        ),
    ]
