# Generated by Django 3.2 on 2022-07-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_videourl_content_type'),
        ('obrazovanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='new_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.videourl'),
        ),
        migrations.AddField(
            model_name='video',
            name='new_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.videourl'),
        ),
    ]
