# Generated by Django 3.2 on 2022-03-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duriation',
            field=models.DurationField(blank=True, default='00:00', verbose_name='Длительность'),
        ),
    ]
