# Generated by Django 3.2.7 on 2021-10-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(blank=True, upload_to='video-image', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video-video', verbose_name='Видео'),
        ),
    ]
