# Generated by Django 3.2 on 2022-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_2',
            field=models.FileField(blank=True, upload_to='video-image', verbose_name='Обложка вторая'),
        ),
    ]
