# Generated by Django 3.2 on 2022-04-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0002_video_duriation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ru',
        ),
    ]
