# Generated by Django 3.2.7 on 2021-10-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0002_report_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
