# Generated by Django 3.2 on 2022-01-15 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obrazovanie', '0002_remove_report_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='favourite',
        ),
        migrations.AddField(
            model_name='report',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='report_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
