# Generated by Django 3.2 on 2022-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0002_video_image_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at', '-views'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at', '-views'], 'verbose_name': 'Видеролик', 'verbose_name_plural': 'Видеролики'},
        ),
        migrations.AddField(
            model_name='video',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
