# Generated by Django 3.2 on 2022-02-08 10:07

import config.yandex_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0002_video_convert_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(storage=config.yandex_storage.ClientDocsStorage, upload_to='video-video', verbose_name='Видео')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_quality',
            field=models.ManyToManyField(related_name='video_qualities', to='obrazovanie.VideoQuality'),
        ),
    ]
