# Generated by Django 3.2 on 2022-03-17 05:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0003_auto_20220315_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Название (каз)'),
        ),
        migrations.AddField(
            model_name='report',
            name='body_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='preview_text_kk',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Короткое описание (каз)'),
        ),
        migrations.AddField(
            model_name='report',
            name='preview_text_ru',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Короткое описание (рус)'),
        ),
        migrations.AddField(
            model_name='report',
            name='title_kk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название (каз)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название (рус)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название (рус)'),
        ),
    ]
