# Generated by Django 3.2 on 2022-02-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0003_auto_20220208_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoquality',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='quality',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='path',
            field=models.CharField(max_length=5000),
        ),
    ]
