# Generated by Django 3.2 on 2022-04-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0003_rename_name_category_name_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='title_ru',
        ),
    ]
