# Generated by Django 3.2 on 2022-07-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0003_rename_new_video_report_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='new_video',
            new_name='video',
        ),
    ]
