# Generated by Django 3.2.7 on 2021-10-11 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obrazovanie', '0003_auto_20211011_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='report_favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='video_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
