# Generated by Django 3.2 on 2022-01-15 17:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obrazovanie', '0003_auto_20220115_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='favourite',
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='video_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='video_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='report_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
