# Generated by Django 3.2 on 2022-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0004_auto_20220208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_quality',
            field=models.ManyToManyField(null=True, related_name='video_qualities', to='obrazovanie.VideoQuality'),
        ),
    ]
