# Generated by Django 3.2 on 2022-04-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0004_rename_title_report_title_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='body',
            new_name='body_ru',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='body',
            new_name='body_ru',
        ),
    ]
