# Generated by Django 3.2.7 on 2021-10-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0004_auto_20211011_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
