# Generated by Django 3.2 on 2022-07-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0004_rename_new_video_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='original_quality',
        ),
    ]
