# Generated by Django 3.2 on 2022-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0004_auto_20220317_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subs_kk',
            field=models.FileField(blank=True, upload_to='video-subs-kk', verbose_name='Субтитры (каз)'),
        ),
    ]
