# Generated by Django 3.2.7 on 2021-10-13 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obrazovanie', '0005_report_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_category', to='obrazovanie.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.FileField(blank=True, upload_to='report-image', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='report',
            name='moderated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название'),
        ),
    ]
