# Generated by Django 3.2 on 2022-03-17 10:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0005_video_subs_kk'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='body_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
