# Generated by Django 3.2 on 2022-02-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0005_alter_video_video_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_quality',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='video',
            name='convert_status',
            field=models.CharField(choices=[('pending', 'Требуется конвертация'), ('started', 'Конвертируется'), ('converted', 'Конвертирован'), ('error', 'Ошибка')], default='pending', max_length=255, verbose_name='Статус конвертации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_quality',
            field=models.ManyToManyField(related_name='video_qualities', to='obrazovanie.VideoQuality'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='height',
            field=models.PositiveIntegerField(null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='path',
            field=models.CharField(max_length=5000, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='quality',
            field=models.PositiveIntegerField(null=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='width',
            field=models.PositiveIntegerField(null=True, verbose_name='Ширина'),
        ),
    ]
