# Generated by Django 3.2 on 2022-01-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0005_videocomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocomment',
            name='report',
        ),
        migrations.AddField(
            model_name='videocomment',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to='obrazovanie.video'),
            preserve_default=False,
        ),
    ]
