# Generated by Django 3.2.7 on 2021-10-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0006_auto_20211013_1034'),
        ('obrazovanie', '0006_auto_20211016_0246'),
    ]

    operations = [
    ]
