# Generated by Django 3.2 on 2022-01-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0006_auto_20220116_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий (cтатьи)', 'verbose_name_plural': 'Комментарии (cтатьи)'},
        ),
    ]
