# Generated by Django 3.2 on 2022-04-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0006_auto_20220404_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название (каз)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название (рус)'),
        ),
    ]
