# Generated by Django 3.2 on 2022-01-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
