# Generated by Django 3.2.7 on 2021-10-16 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obrazovanie', '0007_merge_0006_auto_20211013_1034_0006_auto_20211016_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
