# Generated by Django 3.2 on 2022-04-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0007_auto_20220404_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='read_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
