# Generated by Django 3.2 on 2022-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0008_report_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='saves',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='saves',
        ),
        migrations.AddField(
            model_name='report',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
