# Generated by Django 3.2 on 2022-01-16 10:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0009_auto_20220116_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
