# Generated by Django 3.2 on 2022-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0010_auto_20220508_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сохранения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='report',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='video',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сохранения'),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
