# Generated by Django 3.2 on 2022-05-12 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0017_report_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=['ru', 'kk'], size=None),
        ),
    ]
