# Generated by Django 3.2 on 2022-05-30 10:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0019_auto_20220530_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(blank=True, default='', max_length=6250, verbose_name='Название видео с расширением'),
        ),
    ]
