# Generated by Django 3.2 on 2022-06-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazovanie', '0021_auto_20220606_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='convert_status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_quality',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube',
        ),
        migrations.DeleteModel(
            name='VideoQuality',
        ),
    ]
