# Generated by Django 3.2 on 2022-05-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_ru', models.CharField(blank=True, default='', max_length=500, verbose_name='Название (рус)')),
                ('name_kk', models.CharField(blank=True, default='', max_length=500, verbose_name='Название (каз)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (каз)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
