# Generated by Django 3.2 on 2022-05-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('size', models.PositiveIntegerField(blank=True, default=38, verbose_name='Размер')),
                ('size_global', models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=6, null=True, verbose_name='Международное обозначение')),
                ('bust', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват груди, см')),
                ('waist', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват талии, см')),
                ('hips', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват бедер, см')),
                ('gender', models.PositiveIntegerField(blank=True, choices=[(0, 'Женский'), (1, 'Мужской'), (2, 'Унисекс')], default=2, verbose_name='Пол')),
                ('type', models.PositiveIntegerField(blank=True, choices=[(0, 'Одежда'), (1, 'Головные уборы'), (2, 'Обувь')], default=0, verbose_name='Тип размера')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('count', models.PositiveIntegerField(default=10, verbose_name='Количество доступное')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='shop.product', verbose_name='Продукт')),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsize', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер продукта',
                'verbose_name_plural': 'Размеры продукта',
                'ordering': ['-created_at'],
            },
        ),
    ]
