# Generated by Django 3.2 on 2022-05-09 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220510_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name_ru', models.CharField(blank=True, default='', max_length=500, verbose_name='Название типа товара (рус)')),
                ('name_kk', models.CharField(blank=True, default='', max_length=500, verbose_name='Название типа товара (каз)')),
            ],
            options={
                'verbose_name': 'Состав Продукта',
                'verbose_name_plural': 'Состав Продукта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='care_kk',
            field=models.TextField(blank=True, verbose_name='Уход (каз)'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_ru',
            field=models.TextField(blank=True, verbose_name='Уход (рус)'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='g_token_price',
            field=models.PositiveIntegerField(blank=True, default=149, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=9990),
        ),
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.ManyToManyField(blank=True, null=True, to='shop.ProductCompound'),
        ),
    ]
