# Generated by Django 3.2 on 2022-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220510_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.ManyToManyField(blank=True, to='shop.ProductCompound'),
        ),
    ]
