# Generated by Django 3.2 on 2022-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена (тиын)'),
        ),
    ]
