# Generated by Django 3.2 on 2022-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='null', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_id',
            field=models.CharField(max_length=64, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
