# Generated by Django 3.2 on 2022-05-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_userorder_userorderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorderitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='post_index',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='price',
        ),
    ]
