# Generated by Django 3.2.7 on 2021-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dobro',
            options={'verbose_name': 'Добро', 'verbose_name_plural': 'Добро'},
        ),
        migrations.AddField(
            model_name='dobro',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
