# Generated by Django 3.2 on 2022-01-16 14:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobro',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
