# Generated by Django 3.2 on 2022-01-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobro', '0002_alter_dobro_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dobro',
            old_name='description',
            new_name='body',
        ),
    ]
