# Generated by Django 3.2 on 2022-01-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobro', '0003_rename_description_dobro_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobro',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
