# Generated by Django 3.2 on 2022-05-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edu_place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='garysh.jpg', null=True, upload_to='profile', verbose_name='Фото'),
        ),
    ]
