# Generated by Django 3.2.7 on 2021-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211001_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='terms_ofuser',
        ),
        migrations.AddField(
            model_name='user',
            name='terms_ofuser',
            field=models.BooleanField(default=False),
        ),
    ]
