# Generated by Django 3.2 on 2022-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220223_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='terms_ofuser',
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
