# Generated by Django 3.2 on 2022-06-03 08:03

import common.yandex_storage
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('video_file', models.FileField(null=True, storage=common.yandex_storage.ClientDocsStorage, upload_to='video-file', verbose_name='Видеофайл')),
                ('original_quality', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Качество')),
                ('convert_status', models.CharField(choices=[('pending', 'Требуется конвертация'), ('started', 'Конвертируется'), ('converted', 'Конвертирован'), ('error', 'Ошибка')], default='pending', max_length=255, verbose_name='Статус конвертации')),
                ('duriation', models.DurationField(blank=True, default=None, null=True, verbose_name='Длительность')),
                ('thumbs', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(null=True, storage=common.yandex_storage.ClientDocsStorage, upload_to='video-file/thumbs', verbose_name='thumbs'), size=None)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'VideoFile',
                'verbose_name_plural': 'VideoFiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
