# Generated by Django 3.2 on 2022-06-06 11:10

import common.yandex_storage
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('video', '0002_alter_videofile_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('videofile_name', models.CharField(max_length=4096, verbose_name='Видеофайл ')),
                ('original_quality', models.PositiveBigIntegerField(null=True, verbose_name='Качество')),
                ('url', models.URLField(blank=True)),
                ('url_type', models.PositiveIntegerField(choices=[(0, 'html'), (1, 'youtube'), (2, 'vimeo'), (3, 'other')], default='youtube')),
                ('convert_status', models.CharField(choices=[('pending', 'Требуется конвертация'), ('started', 'Конвертируется'), ('converted', 'Конвертирован'), ('error', 'Ошибка')], default='pending', max_length=255, verbose_name='Статус конвертации')),
                ('duriation', models.DurationField(blank=True, default=None, null=True, verbose_name='Длительность')),
                ('thumbs', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(null=True, storage=common.yandex_storage.ClientDocsStorage, upload_to='video-file/thumbs', verbose_name='thumbs'), size=None)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'VideoURL',
                'verbose_name_plural': 'VideoURL',
                'ordering': ['-created_at'],
            },
        ),
    ]
