# Generated by Django 3.2 on 2022-07-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_videourl_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videourl',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='videourl',
            name='object_id',
        ),
    ]
