# Generated by Django 3.2 on 2022-06-06 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_videourl_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videourl',
            name='thumbs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
    ]
