# Generated by Django 3.2 on 2022-06-07 20:45

import common.yandex_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_videourl_thumbs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videourl',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Video'},
        ),
        migrations.AddField(
            model_name='videourl',
            name='video_file',
            field=models.FileField(null=True, storage=common.yandex_storage.ClientDocsStorage, upload_to='video-file', verbose_name='Видеофайл'),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='url_type',
            field=models.PositiveIntegerField(choices=[(0, 'html'), (1, 'youtube'), (2, 'vimeo'), (3, 's3'), (4, 'other')], default='s3'),
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
