# Generated by Django 3.2 on 2022-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20220608_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videourl',
            name='videofile_name',
        ),
        migrations.AddField(
            model_name='videourl',
            name='name',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Название'),
        ),
    ]
