# Generated by Django 3.2 on 2022-06-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20220608_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQualityURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('url', models.URLField(blank=True, unique=True)),
                ('quality', models.PositiveIntegerField(blank=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videourl')),
            ],
            options={
                'verbose_name': 'VideoQualityURL',
                'verbose_name_plural': 'VideoQualityURL',
                'ordering': ['-created_at'],
            },
        ),
    ]
