# Generated by Django 3.2 on 2022-06-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_videoqualityurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoqualityurl',
            name='url',
            field=models.URLField(blank=True, max_length=4096, unique=True),
        ),
    ]
