# Generated by Django 3.2 on 2022-06-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_videoqualityurl_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videourl',
            name='thumbs',
        ),
    ]
