# Generated by Django 3.2 on 2022-06-07 21:38

import common.yandex_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_remove_videourl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videourl',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=common.yandex_storage.ClientDocsStorage, upload_to='video-file', verbose_name='Видеофайл'),
        ),
    ]
