# Generated by Django 3.2 on 2022-06-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_auto_20220608_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoqualityurl',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='video.videourl'),
        ),
    ]
