# Generated by Django 3.2 on 2022-06-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('video', '0016_alter_videourl_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoqualityurl',
            name='url',
            field=models.URLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'id__in': (4, 5, 35, 23, 59)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
