# Generated by Django 3.2 on 2022-06-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_auto_20220622_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videourl',
            name='convert_status',
            field=models.CharField(choices=[('pending', 'Требуется конвертация'), ('downloading', 'Идет загрузка'), ('started', 'Конвертируется'), ('converted', 'Конвертирован'), ('link', 'Ссылка'), ('error', 'Ошибка')], default='pending', max_length=255, verbose_name='Статус конвертации'),
        ),
    ]
