# Generated by Django 3.2 on 2022-06-29 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('object_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Сохранение',
                'verbose_name_plural': 'Сохранения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('bookmarks_count', models.PositiveIntegerField(default=0, verbose_name='Сохранения')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('object_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('bookmarks_count', models.PositiveIntegerField(default=0, verbose_name='Сохранения')),
                ('body', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
