# Generated by Django 3.2 on 2022-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сохранения'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сохранения'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
