# Generated by Django 3.2 on 2022-05-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0003_auto_20220508_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reviews_count',
            new_name='reviews_count',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviews_count',
            new_name='reviews_count',
        ),
    ]
