# Generated by Django 3.2 on 2022-05-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0005_auto_20220508_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сохранение', 'verbose_name_plural': 'Сохранения'},
        ),
    ]
